;; the intent was for the ai not to make the impassable barriers, but it makes it useless. disable the barriers in mechanics somehow.

(defun auto-turn (player)
  (dotimes (x *w*)
    (dotimes (y *h*)
      (found-city-attempt x y player)))
  (dotimes (x *w*)
    (dotimes (y *h*)
      (move-unit-attempt x y 0 -1 player)
      (move-unit-attempt x y 0 1 player)
      (move-unit-attempt x y -1 0 player)
      (move-unit-attempt x y 1 0 player)))
  (dotimes (x *w*)
    (dotimes (y *h*)
      (buy-unit x y player))))
